### ISSUE TITLE
Finalize Tabs Component

### ISSUE THREAD

**Issue by zguo123** [Lu-Entertainment/utmcfsa.org#7]
- [ ] Add tabs for all the frontend pages created so far
- [ ] Add Tabs to each page

**Comment by Sprit-Fun** [comment]
Is the task for the redirection of the tabs on top of the page?

**Comment by zguo123** [comment]
This is the tab for the navbar at the top of the page that contains "Important Links"

**Comment by zguo123** [comment]
> Is the task for the redirection of the tabs on top of the page? 

Yes, not the "Questions" and the "Responses " tab you find at the top of the forms page
